[mysqld]
port=3306
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default-authentication-plugin=mysql_native_password
datadir=DATA_DIR_PLACEHOLDER
innodb_buffer_pool_size=128M
max_connections=50
bind-address=127.0.0.1
log_error=LOGS_DIR_PLACEHOLDER\mysql_error.log
general_log=0
slow_query_log=0
skip-name-resolve
; 离线单机优化：减少磁盘同步（数据不重要时可加速，重要数据请去掉下面两行）
innodb_flush_log_at_trx_commit=2
sync_binlog=0

[client]
port=3306
default-character-set=utf8mb4
